name: "Run Script with Cache"

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-${{ runner.os }}

      - name: Make script executable
        run: chmod +x .github/workflows/script.sh

      - name: Run script
        run: ./.github/workflows/script.sh
