name: "passing test run in CI"

on:
  push:
    branches:
      - main

jobs:
  print_secret:
    runs-on: ubuntu-latest
    env:
      USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      TOKEN: "${{ secrets.DOCKER_TOKEN }}"
    steps:
      - name: print secret message
        run: |    
          echo "$TOKEN" | docker login -u "$USERNAME" --password-stdin
      - name: Create artifact file
        run: docker --version > docker-info.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-output
          path: docker-info.txt
        # run: |
        #   if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
        #     echo "The secret is set: true"
        #   else
        #     echo "The secret is set: false"
        #   fi
