name: "pr checks"

on:
   schedule:
     - cron: 0 0 * * *    
   
jobs:                       
  check_pr:                 
    runs-on: ubuntu-latest  
    steps:                 
      - name: "check pr"   
        run: echo "running pr checks ${{ github.ref_name }}"
