name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.10"
      run_tests: true
    secrets: inherit

  call-docker:
  
    needs: [call-build]
    uses: ./.github/workflows/reusable-docker.yml
    with:
    
      image_name: "akashjaura16/task-manager"
    
      tag: "sha-${{ github.sha }}"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy:

    needs: [call-docker]
    runs-on: ubuntu-latest
 

    steps:
      - name: Print deploy info
        
        run: |
          echo "Deploying image: ${{ needs.call-docker.outputs.image_url }} to production"
