---
name: multi-job
on:
  push:
    branches:
      - main
jobs:
  main-check:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.step1.outputs.date }}
    steps:
      - name: create output
        id: step1
        if: ${{ github.ref =='main' }}
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
  fail-check:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (will fail)
        run: exit 1
      - name: Run only if previous step failed
        if: ${{ failure() }}
        run: echo "Previous step failed!"
  push-check:
    runs-on: ubuntu-latest
   
    steps:
      - name: Run only on push
        if: ${{ github.event_name == 'push' }}
        run: echo "This runs only on push events"
  failevent-check:
    runs-on: ubuntu-latest
    steps:
      - name: Step that may fail
        continue-on-error: true
        run: exit 1
      - name: Next step
        run: echo "Workflow continues"
