name: self-hosted-workflows

on:
  push:
    branches:
      - main

jobs:
  ubuntu-os:
    runs-on: [ self-hosted , my-linux-runner ]
    steps:
      - name: "Print hostname"
        run: hostname
      - name: "print the working directory"
        run: pwd
      - name: Create a file
        run: echo "Hello from self-hosted runner" > hello.txt
      - name: Verify file in runner
        run: ls -l

