
name: "self-hosted-workflows"
on: 
  push:
    branches:
      - main
jobs:
  ubuntu-os:
    runs-on: ubuntu-latest
    steps:
      - name: "check os name"
        run: echo  $RUNNER_OS
      - name: Print hostname
        run:  hostname
      - name:  " The current user running the job "
        run:  whoami
      - name: "docker version"
        run: docker --version
      - name: "python version"
        run: python --version
      - name: "node version"
        run: node --verison
      - name: "git version"
        run: git --version
  mac-os:
    runs-on: macos-latest
    steps:
      - name: "check os name"
        run:  echo $RUNNER_OS
      - name: Print hostname
        run:  hostname
      - name:  " The current user running the job "
        run:  whoami
  windows-os:
    runs-on: macos-latest
    steps:
      - name: "check os name"
        run:  echo $RUNNER_OS
      - name: Print hostname
        run: hostname
      - name:  " The current user running the job "
        run:  whoami
  

  

